name: Lint Markdown

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DavidAnson/markdownlint-cli2-action@v16
      with:
        globs: '**/*.md'
